# GENERAL EQUIPMENT ATTRIBUTES

rarities = {
    "rarity_levels": [
        "normal",
        "common",
        "uncommon",
        "rare",
        "epic",
        "mythical",
    ],
    "rarity_weights": [
        0.535,
        0.255,
        0.125,
        0.055,
        0.029,
        0.001,
    ],
    "rarity_colors": {
        "normal": "white",
        "common": "green",
        "uncommon": "#308CE8",
        "rare": "#FFD700",
        "epic": "#E600E6",
        "mythical": "red"
    },
    "rarity_modifier_counts": {
        "normal": 0,
        "common": 1,
        "uncommon": 2,
        "rare": 3,
        "epic": 4,
        "mythical": 5
    }
}

qualities = [
    "abysmal",
    "awful",
    "bad",
    "poor",
    "fair",
    "normal",
    "fine",
    "good",
    "superior",
    "excellent",
    "exceptional",
    "exquisite",
    "flawless",
]

quality_weights = [
    0.0075,
    0.0125,
    0.025,
    0.05,
    0.1,
    0.5,
    0.15,
    0.0825,
    0.04,
    0.0225,
    0.01,
    0.00375,
    0.001875,
]

# ARMOR ATTRIBUTES

armor_material_names = [
    "hide",
    "leather",
    "boiled leather",
    "studded leather",
    "reinforced leather",
    "shadowed leather",
    "copper",
    "bronze",
    "iron",
    "steel",
    "truesteel",
    "darksteel",
    "orichalcum",
    "mithril",
    "voidstone",
    "brimstone",
    "cold iron",
    "thunderstone",
    "pearlstone",
    "electrum",
    "adamantine",
    "meteoric iron",
]

armor_material_weights = [
    0.1,
    0.11,
    0.09,
    0.08,
    0.06,
    0.05,
    0.12,
    0.11,
    0.1,
    0.08,
    0.01,
    0.02,
    0.02,
    0.02,
    0.0045,
    0.0045,
    0.0045,
    0.0045,
    0.0045,
    0.0045,
    0.0005,
    0.0025,
]

armor_prefixes = [
    "Tempered",
    "Hardened",
    "Unbreakable",
    "Indestructible",
    "Healing",
    "Vampiric",
    "Swift",
    "Quick",
    "Targeting",
    "Lucky",
    "Light",
    "Impervious",
    "Deadly",
    "Vigilant",
    "Blazing",
    "Freezing",
    "Shocking",
    "Sanctified",
    "Abyssal",
    "Esoteric",
    "Venomous",
    "Agile",
    "Stalwart",
    "Robust",
    "Astute",
    "Enlightened",
    "Appealing",
]

armor_prefix_weights = [
    0.12,
    0.06,
    0.03,
    0.015,
    0.08,
    0.05,
    0.08,
    0.04,
    0.08,
    0.06,
    0.06,
    0.03,
    0.025,
    0.05,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.025,
    0.025,
    0.025,
    0.025,
    0.025,
    0.025,
]

armor_suffixes = [
    "of Spikes",
    "of Thorns",
    "of Retaliation",
    "of Strength",
    "of the Juggernaut",
    "of the Hawk",
    "of the Eagle",
    "of the Cat",
    "of the Fox",
    "of Endurance",
    "of Toughness",
    "of the Magi",
    "of the Wizard",
    "of Wisdom",
    "of Piety",
    "of Charisma",
    "of the Silver Tongue",
    "of Fate",
    "of Fortune",
    "of Defense",
    "of the Rampart",
    "of Protection",
    "of the Fortress",
    "of Longevity",
    "of Health",
    "of Life",
    "of Flames",
    "of the Glacier",
    "of Thunder",
    "of the Heavens",
    "of the Void",
    "of the Arcane",
    "of Toxins",
    "of Alacrity",
    "of Evasion",
]

armor_suffix_weights = [
    0.05,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.025,
    0.0125,
    0.09,
    0.04,
    0.09,
    0.04,
    0.075,
    0.0525,
    0.025,
    0.025,
    0.025,
    0.025,
    0.025,
    0.025,
    0.025,
    0.025,
    0.025,
    0.03,
]

# WEAPON ATTRIBUTES

weapon_prefixes = [
    "Deadly",
    "Blazing",
    "Searing",
    "Freezing",
    "Chilled",
    "Frostborn",
    "Fireborn",
    "Shocking",
    "Charged",
    "Thunderstruck",
    "Sanctified",
    "Abyssal",
    "Esoteric",
    "Venomous",
    "Relentless",
    "Murderous",
    "Masterwork",
    "Swift",
    "Quick",
    "Vampiric",
    "Dastardly",
    "Brutal",
    "Barbaric",
    "Bloodthirsty",
    "Demonic",
    "Infernal",
    "Enchanted",
    "Eldritch",
    "Wretched",
    "Sinister",
    "Stoneforged",
    "Skyforged",
]

weapon_prefix_weights = []

weapon_suffixes = [
    "of Alacrity",
    "of Celerity",
    "of Defense",
    "of Protection",
    "of Strength",
    "of the Juggernaut",
    "of the Hawk",
    "of the Eagle",
    "of the Cat",
    "of the Fox",
    "of Endurance",
    "of Toughness",
    "of the Magi",
    "of the Wizard",
    "of Wisdom",
    "of Piety",
    "of Charisma",
    "of the Silver Tongue",
    "of Fate",
    "of Fortune",
    "of Longevity",
    "of Health",
    "of Life",
    "of Flames",
    "of the Glacier",
    "of Thunder",
    "of the Heavens",
    "of the Void",
    "of the Arcane",
    "of Toxins",
    "of Evasion",
    "of Ruin",
    "of Scorching",
    "of Frostbite",
    "of Thunder",
    "of Decay",
    "of Death",
    "of Conflagaration",
    "of Insanity",
    "of Sanctification",
    "of the Slayer",
    "of the Excecutioner",
    "of Fervor",
    "of Voracity",
    "of Cruelty",
    "of Ruthlessness",
    "of Fury",
    "of Slaughter",
    "of Ferocity",
    "of Onslaught",
    "of Wildfire",
    "of Blight",
    "of Destruction",
    "of Devastation",
    "of Annihilation",
    "of Disintegration",
    "of Obliteration",
    "of the Elements",
    "of the Flamecaller",
    "of Shattering",
    "of Torment",
    "of Celestial Wrath",
    "of Mortality",
]

weapon_metal_material_names = [
    "copper",
    "bronze",
    "iron",
    "steel",
    "truesteel",
    "darksteel",
    "orichalcum",
    "mithril",
    "voidstone",
    "brimstone",
    "cold iron",
    "thunderstone",
    "pearlstone",
    "electrum",
    "adamantine",
    "meteoric iron",
]

weapon_metal_material_weights = [
    0.2,
    0.2,
    0.23,
    0.15,
    0.0275,
    0.04,
    0.04,
    0.04,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.005,
    0.0075,
]

weapon_wood_material_names = [
    "maple",
    "ash",
    "elm",
    "oak",
    "hickory",
    "walnut",
    "ironwood",
    "rosewood",
    "juniper",
    "yew",
]

weapon_wood_material_weights = [
    0.2,
    0.18,
    0.16,
    0.14,
    0.12,
    0.075,
    0.05,
    0.025,
    0.025,
    0.025,
]
